// Generated by tools/extract_palette.py from reference.webp. Do not hand-edit.
// Sorted dark -> light. Indices are referenced by name in draw.js.
const PALETTE = [
  '#000112', // 0
  '#000251', // 1
  '#300384', // 2
  '#131f72', // 3
  '#013198', // 4
  '#7e1f8c', // 5
  '#0444b9', // 6
  '#d723b3', // 7
  '#0e78c2', // 8
  '#429dd1', // 9
  '#0fb6dd', // 10
  '#d88fd0', // 11
  '#1edde4', // 12
  '#4de8ec', // 13
  '#aef0f5', // 14
  '#f6f9f6', // 15
];
