"""Extract a 16-color palette from the reference lab scene and write palette.js.

Usage: python3 tools/extract_palette.py [reference image] [colors]

The reference is lossy, so we first over-quantize (median cut, 64 bins) to
collapse compression noise, then greedily pick the final colors with a
weighted farthest-point rule: score = pixel_count * (distance to nearest
already-picked color)^2. This keeps the dominant navies while still pulling
in the small neon accents (cyan, magenta, pink) that a pure frequency sort
would drop.
"""
import sys
from PIL import Image

SRC = sys.argv[1] if len(sys.argv) > 1 else "reference.gif"
N = int(sys.argv[2]) if len(sys.argv) > 2 else 16


def dist2(a, b):
    # Weighted RGB ("redmean") distance; cheap and good enough for picking.
    rm = (a[0] + b[0]) / 2
    dr, dg, db = a[0] - b[0], a[1] - b[1], a[2] - b[2]
    return (2 + rm / 256) * dr * dr + 4 * dg * dg + (2 + (255 - rm) / 256) * db * db


def luma(c):
    return 0.2126 * c[0] + 0.7152 * c[1] + 0.0722 * c[2]


im = Image.open(SRC)
frames = getattr(im, "n_frames", 1)
counts = {}
for f in range(frames):
    im.seek(f)
    q = im.convert("RGB").quantize(colors=64, method=Image.Quantize.MEDIANCUT)
    pal = q.getpalette()
    for n, i in q.getcolors():
        c = tuple(pal[i * 3:i * 3 + 3])
        counts[c] = counts.get(c, 0) + n

cands = sorted(counts.items(), key=lambda kv: -kv[1])
picked = [cands[0][0]]
while len(picked) < N:
    best = max(
        (c for c, _ in cands if c not in picked),
        key=lambda c: counts[c] * min(dist2(c, p) for p in picked),
    )
    picked.append(best)

picked.sort(key=luma)
hexes = ["#%02x%02x%02x" % c for c in picked]

with open("palette.js", "w") as fh:
    fh.write("// Generated by tools/extract_palette.py from %s. Do not hand-edit.\n" % SRC)
    fh.write("// Sorted dark -> light. Indices are referenced by name in draw.js.\n")
    fh.write("const PALETTE = [\n")
    for i, h in enumerate(hexes):
        fh.write("  '%s', // %d\n" % (h, i))
    fh.write("];\n")
print("\n".join(hexes))
